### ISSUE TITLE
[DesignProposal]: Pipeline Templating

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#523]
### Background and Motivation

1. Support pipeline template;
2. Simplify pipeline development;

#### Templating 

Example:
```YAML
name: 'video_cap'
variables:
    scale: 0.2
    input_op: 'towheeoperator/imread' <-- default value for template variable
    input_op_help_: 'input operator'  <-- help text for template variable, which will be shown during inspecting.
operators:
    -
        name: 'read_image'
        function: '{input_op}' <-- template variable
        init_args:
            scale: {scale}
        inputs:
        outputs:
        iter_info:
            type: map
```

A container section is introduced for template variables. Users can refer to these variables in their pipeline. The template rendering result:

```YAML
name: 'video_cap'
variables:
    scale: 0.2
    input_op: 'towheeoperator/imread'
operators:
    -
        name: 'read_image'
        function: 'towheeoperator/imread' <-- template variable is replaced by variable value
        init_args:
            scale: 0.2
        inputs:
        outputs:
        iter_info:
            type: map
```

modify variables from command line
```shell 
$ towhee execute -Dvariables.scale=1.0 --dry_run video_cap/video_cap_template.yaml
```
modify variables from python code
```python
 with param_scope() as hp:
     hp.variables.scale=1.0
     pipe = pipeline('dir/pipeline_template')
```

```python     
with param_scope('variables.scale=1.0'):
    pipe = pipeline('dir/pipeline_template')
```

templating API

```python
pipe = Builder(scale=1.0, input_op='towheeoperator/imread')
           .pipeline('dir/pipeline_template')
```

inspecting API
``` python
pipe = pipeline('dir/pipeline_template')
help(pipe) # showing all template variables and their help text
```

#### Injecting

Injecting allows modifying a pipeline directly without declaring template variables. This means any towhee pipeline can be used as a template. For example:

```YAML
name: 'video_cap'
operators:
    -
        name: 'read_image'
        function: 'towheeoperator/imread' <-- injecting point
        init_args:                         <-- another injecting point
            scale: 0.2
        inputs:
        outputs:
        iter_info:
            type: map
```

Users can modify the pipeline by injecting API:
```python
 with param_scope() as hp:
     hp.read_image.function='myns/my_imread'
     hp.read_image.init_args=dict(sclae=1.0, gray=True)
     pipe = Injector().pipeline('dir/pipeline_template')
```
rendering result:

```YAML
name: 'video_cap'
operators:
    -
        name: 'read_image'
        function: 'myns/my_imread' <-- injecting result, value at injecting point is replaced
        init_args:                  <-- injecting also support complex value
            scale: 1.0
            gray: True
        inputs:
        outputs:
        iter_info:
            type: map
```

### Pros and Cons

1. Simplify pipeline development;
2. Support hyper-parameter tuning;
